/*
这段代码的部分最初来源于 GTA V SCRIPT HOOK SDK。
http://dev-c.com
(C) Alexander Blade 2015

它现在已成为 Enhanced Native Trainer 项目的一部分。
https://github.com/gtav-ent/GTAV-EnhancedNativeTrainer
(C) Sondai Smith 及贡献者 2015
*/

#pragma once

#include "..\..\inc\natives.h"
#include "..\..\inc\types.h"
#include "..\..\inc\enums.h"
#include "..\..\inc\main.h"
#include "..\ui_support\menu_functions.h"
#include "..\storage\database.h"
#include <string>
#include <unordered_map>

inline constexpr size_t WEAPON_CATEGORY_COUNT = 8; // 近战/手枪/冲锋枪/步枪/霰弹枪/狙击/重型/投掷

// 统一的武器标签本地化回退：当 UI::_GET_LABEL_TEXT 返回空或 "NULL" 时，使用自定义映射
inline std::string get_weapon_label_with_fallback(const std::string& key) {
	std::string localized;
	if (UI::DOES_TEXT_LABEL_EXIST(const_cast<char*>(key.c_str()))) {
		localized = UI::_GET_LABEL_TEXT(const_cast<char*>(key.c_str()));
	}

	if (localized.empty() || localized == "NULL") {
		static const std::unordered_map<std::string, std::string> kWeaponLabelFallback = {
			{"WT_DIGI", "数字扫描仪"},
			{"WT_BRIEFCASE", "公文包 1"},
			{"WT_BRIEFCASE_02", "公文包 2"},
			{"WT_BRIEFCASE_03", "公文包 3"},
		};
		auto it = kWeaponLabelFallback.find(key);
		if (it != kWeaponLabelFallback.end()) return it->second;
		return key;
	}
	return localized;
}

// 将类似 "\"WEAPON_PISTOL\"" 的字符串规范化为 WEAPON_PISTOL
inline std::string normalize_weapon_model_key(const std::string& in) {
	std::string s = in;	// 复制输入字符串，避免直接修改原始数据

	// 去掉首尾空格或制表符，防止配置文件或输入中存在多余空白字符
	while (!s.empty() && (s.front() == ' ' || s.front() == '\t')) s.erase(s.begin());
	while (!s.empty() && (s.back() == ' ' || s.back() == '\t')) s.pop_back();

	// 去掉包裹字符串的双引号，例如从 "WEAPON_PISTOL" 变成 WEAPON_PISTOL
	if (!s.empty() && s.front() == '"') s.erase(s.begin());
	if (!s.empty() && s.back() == '"') s.pop_back();

	return s;	// 返回处理后的规范化字符串
}

// 注意：依赖 VOV_WEAPON_* 的辅助函数在文件后半段定义，以避免前置声明造成外部链接问题

const std::vector<std::string> MENU_WEAPON_CATEGORIES{ "近战武器", "手枪", " 冲锋枪", " 突击步枪", "霰弹枪", " 狙击步枪", "重型武器", "投掷武器" };

// 计数: 20
const std::vector<std::string> CAPTIONS_MELEE{ "WT_KNIFE", "WT_NGTSTK", "WT_HAMMER", "WT_BAT", "WT_BALL", "WT_DIGI", "WT_GOLFCLUB", "WT_CROWBAR", "WT_BOTTLE", "WT_DAGGER", "WT_HATCHET", "WT_KNUCKLE", "WT_MACHETE", "WT_FLASHLIGHT", "WT_SWBLADE", "WT_BATTLEAXE", "WT_WRENCH", "WT_POOLCUE", "WT_SHATCHET", "WT_METALDETECT", "WT_HACKDEVICE", "WT_CANDYCANE", "WT_STUNROD", "WT_BRIEFCASE", "WT_BRIEFCASE_02", "WT_BRIEFCASE_03" };
const std::vector<std::string> VALUES_MELEE{ "WEAPON_KNIFE", "WEAPON_NIGHTSTICK", "WEAPON_HAMMER", "WEAPON_BAT", "WEAPON_BALL", "WEAPON_DIGISCANNER", "WEAPON_GOLFCLUB", "WEAPON_CROWBAR", "WEAPON_BOTTLE", "WEAPON_DAGGER", "WEAPON_HATCHET", "WEAPON_KNUCKLE", "WEAPON_MACHETE", "WEAPON_FLASHLIGHT", "WEAPON_SWITCHBLADE", "WEAPON_BATTLEAXE", "WEAPON_WRENCH", "WEAPON_POOLCUE", "WEAPON_STONE_HATCHET", "WEAPON_METALDETECTOR", "WEAPON_HACKINGDEVICE", "WEAPON_CANDYCANE", "WEAPON_STUNROD", "WEAPON_BRIEFCASE", "WEAPON_BRIEFCASE_02", "WEAPON_BRIEFCASE_03"};
// 计数: 18
const std::vector<std::string> CAPTIONS_HANDGUN{ "WT_PIST", "WT_PIST2", "WT_PIST_CBT", "WT_PIST_AP", "WT_PIST_50", "WT_SNSPISTOL", "WT_SNSPISTOL2", "WT_HEAVYPSTL", "WT_VPISTOL", "WT_STUN", "WT_FLAREGUN", "WT_MKPISTOL", "WT_REVOLVER", "WT_REVOLVER2", "WT_REV_DA", "WT_RAYPISTOL", "WT_CERPST", "WT_REV_NV", "WT_GDGTPST", "WT_PISTOLXM3" };
const std::vector<std::string> VALUES_HANDGUN{ "WEAPON_PISTOL", "WEAPON_PISTOL_MK2", "WEAPON_COMBATPISTOL", "WEAPON_APPISTOL", "WEAPON_PISTOL50", "WEAPON_SNSPISTOL", "WEAPON_SNSPISTOL_MK2", "WEAPON_HEAVYPISTOL", "WEAPON_VINTAGEPISTOL", "WEAPON_STUNGUN", "WEAPON_FLAREGUN", "WEAPON_MARKSMANPISTOL", "WEAPON_REVOLVER", "WEAPON_REVOLVER_MK2", "WEAPON_DOUBLEACTION", "WEAPON_RAYPISTOL", "WEAPON_CERAMICPISTOL", "WEAPON_NAVYREVOLVER", "WEAPON_GADGETPISTOL", "WEAPON_PISTOLXM3" };
// 计数: 10
const std::vector<std::string> CAPTIONS_SUBMACHINE{ "WT_SMG_MCR", "WT_SMG", "WT_SMG2", "WT_SMG_ASL", "WT_MG", "WT_MG_CBT", "WT_MG_CBT2", "WT_GUSENBERG", "WT_COMBATPDW", "WT_MCHPIST", "WT_MINISMG", "WT_TECPISTOL" };
const std::vector<std::string> VALUES_SUBMACHINE{ "WEAPON_MICROSMG", "WEAPON_SMG", "WEAPON_SMG_MK2", "WEAPON_ASSAULTSMG", "WEAPON_MG", "WEAPON_COMBATMG", "WEAPON_COMBATMG_MK2", "WEAPON_GUSENBERG", "WEAPON_COMBATPDW", "WEAPON_MACHINEPISTOL", "WEAPON_MINISMG", "WEAPON_TECPISTOL" };
// 计数: 11
const std::vector<std::string> CAPTIONS_ASSAULT{ "WT_RIFLE_ASL", "WT_RIFLE_ASL2", "WT_BULLRIFLE2", "WT_RIFLE_CBN", "WT_RIFLE_CBN2", "WT_RIFLE_ADV", "WT_RIFLE_SCBN", "WT_SPCARBINE2", "WT_BULLRIFLE", "WT_CMPRIFLE", "WT_RAYCARBINE", "WT_MLTRYRFL", "WT_HEAVYRIFLE", "WT_TACRIFLE", "WT_BATTLERIFLE" };
const std::vector<std::string> VALUES_ASSAULT{ "WEAPON_ASSAULTRIFLE", "WEAPON_ASSAULTRIFLE_MK2", "WEAPON_BULLPUPRIFLE_MK2", "WEAPON_CARBINERIFLE", "WEAPON_CARBINERIFLE_MK2", "WEAPON_ADVANCEDRIFLE", "WEAPON_SPECIALCARBINE", "WEAPON_SPECIALCARBINE_MK2", "WEAPON_BULLPUPRIFLE", "WEAPON_COMPACTRIFLE", "WEAPON_RAYCARBINE", "WEAPON_MILITARYRIFLE", "WEAPON_HEAVYRIFLE", "WEAPON_TACTICALRIFLE", "WEAPON_BATTLERIFLE" };
// 计数: 9
const std::vector<std::string> CAPTIONS_SHOTGUN{ "WT_SG_PMP", "WT_SG_PMP2", "WT_SG_SOF", "WT_SG_BLP", "WT_SG_ASL", "WT_MUSKET", "WT_HVYSHOT", "WT_DBSHGN", "WT_AUTOSHGN", "WT_CMBSHGN" };
const std::vector<std::string> VALUES_SHOTGUN{ "WEAPON_PUMPSHOTGUN", "WEAPON_PUMPSHOTGUN_MK2", "WEAPON_SAWNOFFSHOTGUN", "WEAPON_BULLPUPSHOTGUN", "WEAPON_ASSAULTSHOTGUN", "WEAPON_MUSKET", "WEAPON_HEAVYSHOTGUN", "WEAPON_DBSHOTGUN", "WEAPON_AUTOSHOTGUN", "WEAPON_COMBATSHOTGUN" };
// 计数: 3
const std::vector<std::string> CAPTIONS_SNIPER{ "WT_SNIP_RIF", "WT_SNIP_HVY", "WT_SNIP_HVY2", "WT_MKRIFLE", "WT_MKRIFLE2", "WT_PRCSRIFLE" };
const std::vector<std::string> VALUES_SNIPER{ "WEAPON_SNIPERRIFLE", "WEAPON_HEAVYSNIPER", "WEAPON_HEAVYSNIPER_MK2", "WEAPON_MARKSMANRIFLE", "WEAPON_MARKSMANRIFLE_MK2", "WEAPON_PRECISIONRIFLE" };
// 计数: 9
const std::vector<std::string> CAPTIONS_HEAVY{ "WT_GL", "WT_GL_SMOKE", "WT_RPG", "WT_MINIGUN", "WT_FIREWRK", "WT_RAILGUN", "WT_HOMLNCH", "WT_CMPGL", "WT_RAYMINIGUN", "WT_EMPL"/*, "WT_RAILGUNXM3"*/, "WT_SNOWLNCHR"};
const std::vector<std::string> VALUES_HEAVY{ "WEAPON_GRENADELAUNCHER", "WEAPON_GRENADELAUNCHER_SMOKE", "WEAPON_RPG", "WEAPON_MINIGUN", "WEAPON_FIREWORK", "WEAPON_RAILGUN", "WEAPON_HOMINGLAUNCHER", "WEAPON_COMPACTLAUNCHER", "WEAPON_RAYMINIGUN", "WEAPON_EMPLAUNCHER"/*, "WEAPON_RAILGUNXM3"*/, "WEAPON_SNOWLAUNCHER"};
// 计数: 11
const std::vector<std::string> CAPTIONS_THROWN{ "WT_GNADE", "WT_GNADE_STK", "WT_PRXMINE", "WT_BZGAS","WT_GNADE_SMK", "WT_MOLOTOV", "WT_FIRE", "WT_PETROL", "WT_SNWBALL", "WT_FLARE", "WT_PIPEBOMB", "WT_HAZARDCAN", "WT_FERTILIZERCAN", "WT_ACIDPACKAGE" };
const std::vector<std::string> VALUES_THROWN{ "WEAPON_GRENADE", "WEAPON_STICKYBOMB", "WEAPON_PROXMINE", "WEAPON_BZGAS","WEAPON_SMOKEGRENADE", "WEAPON_MOLOTOV", "WEAPON_FIREEXTINGUISHER", "WEAPON_PETROLCAN", "WEAPON_SNOWBALL", "WEAPON_FLARE", "WEAPON_PIPEBOMB", "WEAPON_HAZARDCAN", "WEAPON_FERTILIZERCAN", "WEAPON_ACIDPACKAGE" };


const std::vector<std::string> VOV_WEAPON_CAPTIONS[] = {CAPTIONS_MELEE, CAPTIONS_HANDGUN, CAPTIONS_SUBMACHINE, CAPTIONS_ASSAULT, CAPTIONS_SHOTGUN, CAPTIONS_SNIPER, CAPTIONS_HEAVY, CAPTIONS_THROWN};
const std::vector<std::string> VOV_WEAPON_VALUES[] = {VALUES_MELEE, VALUES_HANDGUN, VALUES_SUBMACHINE, VALUES_ASSAULT, VALUES_SHOTGUN, VALUES_SNIPER, VALUES_HEAVY, VALUES_THROWN};

// 全局静态映射（只初始化一次，兼容原 VOV_WEAPON_VALUES / VOV_WEAPON_CAPTIONS）
inline const std::unordered_map<std::string, std::string>& get_weapon_caption_map() {
	static std::unordered_map<std::string, std::string> map;
	if (map.empty()) {
		// 1. 遍历原项目的武器表
		for (size_t cat = 0; cat < WEAPON_CATEGORY_COUNT; ++cat) {
			const auto& values = VOV_WEAPON_VALUES[cat];
			const auto& captions = VOV_WEAPON_CAPTIONS[cat];
			for (size_t i = 0; i < values.size(); ++i) {
				if (i < captions.size()) {
					map[values[i]] = captions[i];
				} else {
					map[values[i]] = ""; // 数据不一致时留空
				}
			}
		}

		// 2. 添加车辆武器/特殊武器映射
		static const std::unordered_map<std::string, std::string> kVehicleWeaponDisplay = {
			{"VEHICLE_WEAPON_MINE_KINETIC", "动能地雷"},
			{"VEHICLE_WEAPON_MINE_SPIKE", "钉刺地雷"},
			{"VEHICLE_WEAPON_MINE_EMP", "电磁脉冲地雷"},
			{"VEHICLE_WEAPON_MINE", "地雷"},
			{"VEHICLE_WEAPON_MINE_SLICK", "滑油地雷"},
			{"VEHICLE_WEAPON_MINE_TAR", "沥青地雷"},
			{"VEHICLE_WEAPON_PLAYER_BULLET", "车载重机枪"},
			{"VEHICLE_WEAPON_PLAYER_LAZER", "超能激光炮"},
			{"WEAPON_UNARMED", "徒手/拳头"},
		};
		map.insert(kVehicleWeaponDisplay.begin(), kVehicleWeaponDisplay.end());
	}
	return map;
}

// 根据模型名获取本地化标题
inline std::string localized_caption_from_model(const std::string& modelIn) {
	std::string m = normalize_weapon_model_key(modelIn);
	if (m == "关") return m;
	const auto& map = get_weapon_caption_map();
	auto it = map.find(m);
	if (it != map.end()) {
		if (!it->second.empty()) {
			return get_weapon_label_with_fallback(it->second);
		}
		return m; // 映射为空，返回原模型名
	}
	return m;// 都没找到，返回原模型名
}

// 批量本地化（与原列表顺序一致）
inline std::vector<std::string> localize_weapon_models(const std::vector<std::string>& models) {
	std::vector<std::string> out;
	out.reserve(models.size());
	for (const auto& s : models) {
		out.push_back(localized_caption_from_model(s));
	}
	return out;
}

// 武器涂装
const std::vector<std::string> CAPTIONS_TINT{ "正常", "绿色", "金色", "粉色", "军绿色", "洛圣都警察局", "橙色", "铂金色" };
const std::vector<int> VALUES_TINT{ 0, 1, 2, 3, 4, 5, 6, 7 };

// MK2 武器涂装
const std::vector<std::string> CAPTIONS_TINT_MK2{ "经典黑色", "经典灰色", "经典双色调", "经典白色", "经典米色", "经典绿色", "经典蓝色", "经典土棕色", "经典棕黑双色", "红色对比", "蓝色对比", "黄色对比", "橙色对比", "鲜艳粉红色", "鲜艳紫黄双色", "鲜艳橙色", "鲜艳绿紫双色", "鲜艳红色元素", "鲜艳绿色元素", "鲜艳青色元素", "鲜艳黄色元素", "鲜艳红白双色", "鲜艳蓝白双色", "金属质感金色", "金属质感铂金色", "金属质感灰紫双色", "金属质感紫绿双色", "金属质感红色", "金属质感绿色", "金属质感蓝色", "金属质感白青双色", "金属质感红黄双色" };

// 手枪
const std::vector<std::string> CAPTIONS_ATTACH_PISTOL{ "WCT_CLIP1", "WCT_CLIP2", "WCT_FLASH", "WCT_SUPP", "WCT_VAR_GOLD" };
const std::vector<std::string> VALUES_ATTACH_PISTOL{ "COMPONENT_PISTOL_CLIP_01", "COMPONENT_PISTOL_CLIP_02", "COMPONENT_AT_PI_FLSH", "COMPONENT_AT_PI_SUPP_02", "COMPONENT_PISTOL_VARMOD_LUXE" };

const std::vector<std::string> CAPTIONS_ATTACH_COMBATPISTOL{ "WCT_CLIP1", "WCT_CLIP2", "WCT_FLASH", "WCT_SUPP", "WCT_VAR_GOLD" };
const std::vector<std::string> VALUES_ATTACH_COMBATPISTOL{ "COMPONENT_COMBATPISTOL_CLIP_01", "COMPONENT_COMBATPISTOL_CLIP_02", "COMPONENT_AT_PI_FLSH", "COMPONENT_AT_PI_SUPP", "COMPONENT_COMBATPISTOL_VARMOD_LOWRIDER" };

const std::vector<std::string> CAPTIONS_ATTACH_APPISTOL{ "WCT_CLIP1", "WCT_CLIP2", "WCT_FLASH", "WCT_SUPP", "WCT_VAR_METAL" };
const std::vector<std::string> VALUES_ATTACH_APPISTOL{ "COMPONENT_APPISTOL_CLIP_01", "COMPONENT_APPISTOL_CLIP_02", "COMPONENT_AT_PI_FLSH", "COMPONENT_AT_PI_SUPP", "COMPONENT_APPISTOL_VARMOD_LUXE" };

const std::vector<std::string> CAPTIONS_ATTACH_PISTOL50{ "WCT_CLIP1", "WCT_CLIP2", "WCT_FLASH", "WCT_SUPP", "WCT_VAR_SIL" };
const std::vector<std::string> VALUES_ATTACH_PISTOL50{ "COMPONENT_PISTOL50_CLIP_01", "COMPONENT_PISTOL50_CLIP_02", "COMPONENT_AT_PI_FLSH", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_PISTOL50_VARMOD_LUXE" };

// 冲锋枪
const std::vector<std::string> CAPTIONS_ATTACH_MICROSMG{ "WCT_CLIP1", "WCT_CLIP2", "WCT_FLASH", "WCT_SCOPE_MAC", "WCT_SUPP", "WCT_VAR_GOLD" };
const std::vector<std::string> VALUES_ATTACH_MICROSMG{ "COMPONENT_MICROSMG_CLIP_01", "COMPONENT_MICROSMG_CLIP_02", "COMPONENT_AT_PI_FLSH", "COMPONENT_AT_SCOPE_MACRO", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_MICROSMG_VARMOD_LUXE" };

const std::vector<std::string> CAPTIONS_ATTACH_SMG{ "WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_DRM", "WCT_FLASH", "WCT_SCOPE_MAC", "WCT_SUPP", "WCT_VAR_GOLD" };
const std::vector<std::string> VALUES_ATTACH_SMG{ "COMPONENT_SMG_CLIP_01", "COMPONENT_SMG_CLIP_02", "COMPONENT_SMG_CLIP_03", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SCOPE_MACRO_02", "COMPONENT_AT_PI_SUPP", "COMPONENT_SMG_VARMOD_LUXE" };

const std::vector<std::string> CAPTIONS_ATTACH_ASSAULTSMG{ "WCT_CLIP1", "WCT_CLIP2", "WCT_FLASH", "WCT_SCOPE_MAC", "WCT_SUPP", "WCT_VAR_GOLD" };
const std::vector<std::string> VALUES_ATTACH_ASSAULTSMG{ "COMPONENT_ASSAULTSMG_CLIP_01", "COMPONENT_ASSAULTSMG_CLIP_02", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SCOPE_MACRO", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_ASSAULTSMG_VARMOD_LOWRIDER" };

// 步枪
const std::vector<std::string> CAPTIONS_ATTACH_ASSAULTRIFLE{ "WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_DRM", "WCT_FLASH", "WCT_SCOPE_MAC", "WCT_SUPP", "WCT_GRIP", "WCT_VAR_GOLD" };
const std::vector<std::string> VALUES_ATTACH_ASSAULTRIFLE{ "COMPONENT_ASSAULTRIFLE_CLIP_01", "COMPONENT_ASSAULTRIFLE_CLIP_02", "COMPONENT_ASSAULTRIFLE_CLIP_03", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SCOPE_MACRO", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_AT_AR_AFGRIP", "COMPONENT_ASSAULTRIFLE_VARMOD_LUXE" };

const std::vector<std::string> CAPTIONS_ATTACH_CARBINERIFLE{ "WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_DRM", "WCT_FLASH", "WCT_SCOPE_MAC", "WCT_SUPP", "WCT_GRIP", "WCT_VAR_GOLD" };
const std::vector<std::string> VALUES_ATTACH_CARBINERIFLE{ "COMPONENT_CARBINERIFLE_CLIP_01", "COMPONENT_CARBINERIFLE_CLIP_02", "COMPONENT_CARBINERIFLE_CLIP_03", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SCOPE_MEDIUM", "COMPONENT_AT_AR_SUPP", "COMPONENT_AT_AR_AFGRIP", "COMPONENT_CARBINERIFLE_VARMOD_LUXE" };

const std::vector<std::string> CAPTIONS_ATTACH_ADVANCEDRIFLE{ "WCT_CLIP1", "WCT_CLIP2", "WCT_FLASH", "WCT_SCOPE_MAC", "WCT_SUPP", "WCT_VAR_METAL" };
const std::vector<std::string> VALUES_ATTACH_ADVANCEDRIFLE{ "COMPONENT_ADVANCEDRIFLE_CLIP_01", "COMPONENT_ADVANCEDRIFLE_CLIP_02", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SCOPE_SMALL", "COMPONENT_AT_AR_SUPP", "COMPONENT_ADVANCEDRIFLE_VARMOD_LUXE" };

// 机枪
const std::vector<std::string> CAPTIONS_ATTACH_MG{ "WCT_CLIP1", "WCT_CLIP2", "WCT_SCOPE_MAC", "WCT_VAR_GOLD" };
const std::vector<std::string> VALUES_ATTACH_MG{ "COMPONENT_MG_CLIP_01", "COMPONENT_MG_CLIP_02", "COMPONENT_AT_SCOPE_SMALL_02", "COMPONENT_MG_VARMOD_LOWRIDER" };

const std::vector<std::string> CAPTIONS_ATTACH_COMBATMG{ "WCT_CLIP1", "WCT_CLIP2", "WCT_SCOPE_MAC", "WCT_GRIP", "WCT_VAR_ETCHM" };
const std::vector<std::string> VALUES_ATTACH_COMBATMG{ "COMPONENT_COMBATMG_CLIP_01", "COMPONENT_COMBATMG_CLIP_02", "COMPONENT_AT_SCOPE_MEDIUM", "COMPONENT_AT_AR_AFGRIP", "COMPONENT_COMBATMG_VARMOD_LOWRIDER" };

// 霰弹枪
const std::vector<std::string> CAPTIONS_ATTACH_PUMPSHOTGUN{ "WCT_FLASH", "WCT_SUPP", "WCT_VAR_GOLD" };
const std::vector<std::string> VALUES_ATTACH_PUMPSHOTGUN{ "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SR_SUPP", "COMPONENT_PUMPSHOTGUN_VARMOD_LOWRIDER" };

const std::vector<std::string> CAPTIONS_ATTACH_SAWNOFF{ "WCT_VAR_METAL" };
const std::vector<std::string> VALUES_ATTACH_SAWNOFF{ "COMPONENT_SAWNOFFSHOTGUN_VARMOD_LUXE" };

const std::vector<std::string> CAPTIONS_ATTACH_ASSAULTSHOTGUN{ "WCT_CLIP1", "WCT_CLIP2", "WCT_FLASH", "WCT_SUPP", "WCT_GRIP" };
const std::vector<std::string> VALUES_ATTACH_ASSAULTSHOTGUN{ "COMPONENT_ASSAULTSHOTGUN_CLIP_01", "COMPONENT_ASSAULTSHOTGUN_CLIP_02", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_AR_SUPP", "COMPONENT_AT_AR_AFGRIP" };

const std::vector<std::string> CAPTIONS_ATTACH_BULLPUPSHOTGUN{ "WCT_FLASH", "WCT_SUPP", "WCT_GRIP" };
const std::vector<std::string> VALUES_ATTACH_BULLPUPSHOTGUN{ "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_AT_AR_AFGRIP" };

// 狙击步枪
const std::vector<std::string> CAPTIONS_ATTACH_SNIPERRIFLE{ "WCT_CLIP1", "WCT_SUPP", "WCT_SCOPE_LRG", "WCT_SCOPE_MAX", "WCT_VAR_WOOD" };
const std::vector<std::string> VALUES_ATTACH_SNIPERRIFLE{ "COMPONENT_SNIPERRIFLE_CLIP_01", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_AT_SCOPE_LARGE", "COMPONENT_AT_SCOPE_MAX", "COMPONENT_SNIPERRIFLE_VARMOD_LUXE" };

const std::vector<std::string> CAPTIONS_ATTACH_HEAVYSNIPER{ "WCT_SCOPE_LRG", "WCT_SCOPE_MAX" }; 
const std::vector<std::string> VALUES_ATTACH_HEAVYSNIPER{ "COMPONENT_AT_SCOPE_LARGE", "COMPONENT_AT_SCOPE_MAX" };

// 重型武器
const std::vector<std::string> CAPTIONS_ATTACH_GRENADELAUNCHER{ "WCT_CLIP1", "WCT_FLASH", "WCT_GRIP", "WCT_SCOPE_MAC" };
const std::vector<std::string> VALUES_ATTACH_GRENADELAUNCHER{ "COMPONENT_GRENADELAUNCHER_CLIP_01", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_AR_AFGRIP", "COMPONENT_AT_SCOPE_SMALL" };

const std::vector<std::string> CAPTIONS_ATTACH_HEAVYRIFLE{ "WCT_CLIP1", "WCT_CLIP2", "WCT_HVYRFLE_SIG", "WCT_SCOPE_LRG", "WCT_FLASH", "WCT_SUPP", "WCT_GRIP", "WCT_VAR_FAM" };
const std::vector<std::string> VALUES_ATTACH_HEAVYRIFLE{ "COMPONENT_HEAVYRIFLE_CLIP_01", "COMPONENT_HEAVYRIFLE_CLIP_02", "COMPONENT_HEAVYRIFLE_SIGHT_01", "COMPONENT_AT_SCOPE_MEDIUM", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_AR_SUPP", "COMPONENT_AT_AR_AFGRIP", "COMPONENT_HEAVYRIFLE_CAMO1" };


// DLC 武器
const std::vector<std::string> CAPTIONS_ATTACH_BULLPUPRIFLE{ "WCT_CLIP1", "WCT_CLIP2", "WCT_FLASH", "WCT_SCOPE_MAC", "WCT_SUPP", "WCT_GRIP", "WCT_VAR_METAL" };
const std::vector<std::string> VALUES_ATTACH_BULLPUPRIFLE{ "COMPONENT_BULLPUPRIFLE_CLIP_01", "COMPONENT_BULLPUPRIFLE_CLIP_02", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SCOPE_SMALL", "COMPONENT_AT_AR_SUPP", "COMPONENT_AT_AR_AFGRIP", "COMPONENT_BULLPUPRIFLE_VARMOD_LOW" };

const std::vector<std::string> CAPTIONS_ATTACH_COMBATPDW{ "WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_DRM", "WCT_FLASH", "WCT_GRIP", "WCT_SCOPE_SML" };
const std::vector<std::string> VALUES_ATTACH_COMBATPDW{ "COMPONENT_COMBATPDW_CLIP_01", "COMPONENT_COMBATPDW_CLIP_02", "COMPONENT_COMBATPDW_CLIP_03", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_AR_AFGRIP", "COMPONENT_AT_SCOPE_SMALL" };

const std::vector<std::string> CAPTIONS_ATTACH_COMPACTRIFLE{ "WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_DRM" };
const std::vector<std::string> VALUES_ATTACH_COMPACTRIFLE{ "COMPONENT_COMPACTRIFLE_CLIP_01", "COMPONENT_COMPACTRIFLE_CLIP_02", "COMPONENT_COMPACTRIFLE_CLIP_03" };

const std::vector<std::string> CAPTIONS_ATTACH_GUSENBERG{ "WCT_CLIP1", "WCT_CLIP2" };
const std::vector<std::string> VALUES_ATTACH_GUSENBERG{ "COMPONENT_GUSENBERG_CLIP_01", "COMPONENT_GUSENBERG_CLIP_02" };

const std::vector<std::string> CAPTIONS_ATTACH_HEAVYPISTOL{ "WCT_CLIP1", "WCT_CLIP2", "WCT_FLASH", "WCT_SUPP", "WCT_VAR_WOOD" };
const std::vector<std::string> VALUES_ATTACH_HEAVYPISTOL{ "COMPONENT_HEAVYPISTOL_CLIP_01", "COMPONENT_HEAVYPISTOL_CLIP_02", "COMPONENT_AT_PI_FLSH", "COMPONENT_AT_PI_SUPP", "COMPONENT_HEAVYPISTOL_VARMOD_LUXE" };

const std::vector<std::string> CAPTIONS_ATTACH_HEAVYSHOTGUN{ "WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_DRM", "WCT_FLASH", "WCT_SUPP", "WCT_GRIP" };
const std::vector<std::string> VALUES_ATTACH_HEAVYSHOTGUN{ "COMPONENT_HEAVYSHOTGUN_CLIP_01", "COMPONENT_HEAVYSHOTGUN_CLIP_02", "COMPONENT_HEAVYSHOTGUN_CLIP_03", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_AT_AR_AFGRIP" };

const std::vector<std::string> CAPTIONS_ATTACH_KNUCKLES{ "WCT_KNUCK_01", "WCT_KNUCK_02", "WCT_KNUCK_BG", "WCT_KNUCK_DLR", "WCT_KNUCK_DMD", "WCT_KNUCK_HT", "WCT_KNUCK_LV", "WCT_KNUCK_PC", "WCT_KNUCK_SLG", "WCT_KNUCK_VG" };
const std::vector<std::string> VALUES_ATTACH_KNUCKLES{ "COMPONENT_KNUCKLE_VARMOD_BASE", "COMPONENT_KNUCKLE_VARMOD_PIMP", "COMPONENT_KNUCKLE_VARMOD_BALLAS", "COMPONENT_KNUCKLE_VARMOD_DOLLAR", "COMPONENT_KNUCKLE_VARMOD_DIAMOND", "COMPONENT_KNUCKLE_VARMOD_HATE", "COMPONENT_KNUCKLE_VARMOD_LOVE", "COMPONENT_KNUCKLE_VARMOD_PLAYER", "COMPONENT_KNUCKLE_VARMOD_KING", "COMPONENT_KNUCKLE_VARMOD_VAGOS" };

const std::vector<std::string> CAPTIONS_ATTACH_MACHINEPISTOL{ "WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_DRM", "WCT_SUPP" };
const std::vector<std::string> VALUES_ATTACH_MACHINEPISTOL{ "COMPONENT_MACHINEPISTOL_CLIP_01", "COMPONENT_MACHINEPISTOL_CLIP_02", "COMPONENT_MACHINEPISTOL_CLIP_03", "COMPONENT_AT_PI_SUPP" };

const std::vector<std::string> CAPTIONS_ATTACH_MARKSMANRIFLE{ "WCT_CLIP1", "WCT_CLIP2", "WCT_FLASH", "WCT_SUPP", "WCT_GRIP", "WCT_VAR_GOLD" };
const std::vector<std::string> VALUES_ATTACH_MARKSMANRIFLE{ "COMPONENT_MARKSMANRIFLE_CLIP_01", "COMPONENT_MARKSMANRIFLE_CLIP_02", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_AR_SUPP", "COMPONENT_AT_AR_AFGRIP", "COMPONENT_MARKSMANRIFLE_VARMOD_LUXE" };

const std::vector<std::string> CAPTIONS_ATTACH_MINISMG{ "WCT_CLIP1", "WCT_CLIP2" };
const std::vector<std::string> VALUES_ATTACH_MINISMG{ "COMPONENT_MINISMG_CLIP_01", "COMPONENT_MINISMG_CLIP_02" };

const std::vector<std::string> CAPTIONS_ATTACH_REVOLVER{ "WCT_REV_VARB", "WCT_REV_VARG" }; 
const std::vector<std::string> VALUES_ATTACH_REVOLVER{ "COMPONENT_REVOLVER_VARMOD_BOSS", "COMPONENT_REVOLVER_VARMOD_GOON" }; 

const std::vector<std::string> CAPTIONS_ATTACH_SNSPISTOL{ "WCT_CLIP1", "WCT_CLIP2", "WCT_VAR_WOOD" };
const std::vector<std::string> VALUES_ATTACH_SNSPISTOL{ "COMPONENT_SNSPISTOL_CLIP_01", "COMPONENT_SNSPISTOL_CLIP_02", "COMPONENT_SNSPISTOL_VARMOD_LOWRIDER" };

const std::vector<std::string> CAPTIONS_ATTACH_SPECIALCARBINE{ "WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_DRM", "WCT_FLASH", "WCT_SCOPE_MAC", "WCT_SUPP", "WCT_GRIP", "WCT_VAR_ETCHM" };
const std::vector<std::string> VALUES_ATTACH_SPECIALCARBINE{ "COMPONENT_SPECIALCARBINE_CLIP_01", "COMPONENT_SPECIALCARBINE_CLIP_02", "COMPONENT_SPECIALCARBINE_CLIP_03", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SCOPE_MEDIUM", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_AT_AR_AFGRIP", "COMPONENT_SPECIALCARBINE_VARMOD_LOWRIDER" };

const std::vector<std::string> CAPTIONS_ATTACH_SWITCHBLADE{ "WCT_SB_BASE", "WCT_SB_VAR1", "WCT_SB_VAR2" };
const std::vector<std::string> VALUES_ATTACH_SWITCHBLADE{ "COMPONENT_SWITCHBLADE_VARMOD_BASE", "COMPONENT_SWITCHBLADE_VARMOD_VAR1", "COMPONENT_SWITCHBLADE_VARMOD_VAR2" };

const std::vector<std::string> CAPTIONS_ATTACH_VINTAGEPISTOL{ "WCT_CLIP1", "WCT_CLIP2", "WCT_SUPP" };
const std::vector<std::string> VALUES_ATTACH_VINTAGEPISTOL{ "COMPONENT_VINTAGEPISTOL_CLIP_01", "COMPONENT_VINTAGEPISTOL_CLIP_02", "COMPONENT_AT_PI_SUPP" };

const std::vector<std::string> CAPTIONS_ATTACH_WEAPON_TECPISTOL{ "WCT_CLIP1", "WCT_CLIP2", "WCT_SUPP", "WCT_SCOPE_MAC2" };
const std::vector<std::string> VALUES_ATTACH_WEAPON_TECPISTOL{ "COMPONENT_TECPISTOL_CLIP_01", "COMPONENT_TECPISTOL_CLIP_02", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_AT_SCOPE_MACRO" };

/* 军火走私 DLC */
const std::vector<std::string> CAPTIONS_ATTACH_PISTOLMK2{ "WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_TR", "WCT_CLIP_INC", "WCT_CLIP_HP", "WCT_CLIP_FMJ", "WCT_SCOPE_PI", "WCT_FLASH", "WCT_SUPP", "WCT_COMP", "WCT_CAMO_1", "WCT_CAMO_2", "WCT_CAMO_3", "WCT_CAMO_4", "WCT_CAMO_5", "WCT_CAMO_6", "WCT_CAMO_7", "WCT_CAMO_8", "WCT_CAMO_9", "WCT_CAMO_10", "WCT_CAMO_IND", "WCT_CAMO_1", "WCT_CAMO_2", "WCT_CAMO_3", "WCT_CAMO_4", "WCT_CAMO_5", "WCT_CAMO_6", "WCT_CAMO_7", "WCT_CAMO_8", "WCT_CAMO_9", "WCT_CAMO_10", "WCT_CAMO_IND" };
const std::vector<std::string> VALUES_ATTACH_PISTOLMK2{ "COMPONENT_PISTOL_MK2_CLIP_01", "COMPONENT_PISTOL_MK2_CLIP_02", "COMPONENT_PISTOL_MK2_CLIP_TRACER", "COMPONENT_PISTOL_MK2_CLIP_INCENDIARY", "COMPONENT_PISTOL_MK2_CLIP_HOLLOWPOINT", "COMPONENT_PISTOL_MK2_CLIP_FMJ", "COMPONENT_AT_PI_RAIL", "COMPONENT_AT_PI_FLSH_02", "COMPONENT_AT_PI_SUPP_02", "COMPONENT_AT_PI_COMP", "COMPONENT_PISTOL_MK2_CAMO", "COMPONENT_PISTOL_MK2_CAMO_02", "COMPONENT_PISTOL_MK2_CAMO_03", "COMPONENT_PISTOL_MK2_CAMO_04", "COMPONENT_PISTOL_MK2_CAMO_05", "COMPONENT_PISTOL_MK2_CAMO_06", "COMPONENT_PISTOL_MK2_CAMO_07", "COMPONENT_PISTOL_MK2_CAMO_08", "COMPONENT_PISTOL_MK2_CAMO_09", "COMPONENT_PISTOL_MK2_CAMO_10", "COMPONENT_PISTOL_MK2_CAMO_IND_01", "COMPONENT_PISTOL_MK2_CAMO_SLIDE", "COMPONENT_PISTOL_MK2_CAMO_02_SLIDE", "COMPONENT_PISTOL_MK2_CAMO_03_SLIDE", "COMPONENT_PISTOL_MK2_CAMO_04_SLIDE", "COMPONENT_PISTOL_MK2_CAMO_05_SLIDE", "COMPONENT_PISTOL_MK2_CAMO_06_SLIDE", "COMPONENT_PISTOL_MK2_CAMO_07_SLIDE", "COMPONENT_PISTOL_MK2_CAMO_08_SLIDE", "COMPONENT_PISTOL_MK2_CAMO_09_SLIDE", "COMPONENT_PISTOL_MK2_CAMO_10_SLIDE", "COMPONENT_PISTOL_MK2_CAMO_IND_01_SLIDE" };

const std::vector<std::string> CAPTIONS_ATTACH_SMGMK2{ "WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_TR", "WCT_CLIP_INC", "WCT_CLIP_HP", "WCT_CLIP_FMJ", "WCT_FLASH", "WCT_HOLO", "WCT_SCOPE_MAC2", "WCT_SCOPE_SML2", "WCT_SUPP", "WCT_MUZZ1", "WCT_MUZZ2", "WCT_MUZZ3", "WCT_MUZZ4", "WCT_MUZZ5", "WCT_MUZZ6", "WCT_MUZZ7", "WCT_BARR", "WCT_BARR2", "WCT_CAMO_1", "WCT_CAMO_2", "WCT_CAMO_3", "WCT_CAMO_4", "WCT_CAMO_5", "WCT_CAMO_6", "WCT_CAMO_7", "WCT_CAMO_8", "WCT_CAMO_9", "WCT_CAMO_10", "WCT_CAMO_IND" };
const std::vector<std::string> VALUES_ATTACH_SMGMK2{ "COMPONENT_SMG_MK2_CLIP_01", "COMPONENT_SMG_MK2_CLIP_02", "COMPONENT_SMG_MK2_CLIP_TRACER", "COMPONENT_SMG_MK2_CLIP_INCENDIARY", "COMPONENT_SMG_MK2_CLIP_HOLLOWPOINT", "COMPONENT_SMG_MK2_CLIP_FMJ", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SIGHTS_SMG", "COMPONENT_AT_SCOPE_MACRO_02_SMG_MK2", "COMPONENT_AT_SCOPE_SMALL_SMG_MK2", "COMPONENT_AT_PI_SUPP", "COMPONENT_AT_MUZZLE_01", "COMPONENT_AT_MUZZLE_02", "COMPONENT_AT_MUZZLE_03", "COMPONENT_AT_MUZZLE_04", "COMPONENT_AT_MUZZLE_05", "COMPONENT_AT_MUZZLE_06", "COMPONENT_AT_MUZZLE_07", "COMPONENT_AT_SB_BARREL_01", "COMPONENT_AT_SB_BARREL_02", "COMPONENT_SMG_MK2_CAMO", "COMPONENT_SMG_MK2_CAMO_02", "COMPONENT_SMG_MK2_CAMO_03", "COMPONENT_SMG_MK2_CAMO_04", "COMPONENT_SMG_MK2_CAMO_05", "COMPONENT_SMG_MK2_CAMO_06", "COMPONENT_SMG_MK2_CAMO_07", "COMPONENT_SMG_MK2_CAMO_08", "COMPONENT_SMG_MK2_CAMO_09", "COMPONENT_SMG_MK2_CAMO_10", "COMPONENT_SMG_MK2_CAMO_IND_01" };

const std::vector<std::string> CAPTIONS_ATTACH_ASSAULTRIFLEMK2{ "WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_TR", "WCT_CLIP_INC", "WCT_CLIP_AP", "WCT_CLIP_FMJ", "WCT_GRIP", "WCT_FLASH", "WCT_HOLO", "WCT_SCOPE_MAC2", "WCT_SCOPE_MED2", "WCT_SUPP", "WCT_MUZZ1", "WCT_MUZZ2", "WCT_MUZZ3", "WCT_MUZZ4", "WCT_MUZZ5", "WCT_MUZZ6", "WCT_MUZZ7", "WCT_BARR", "WCT_BARR2", "WCT_CAMO_1", "WCT_CAMO_2", "WCT_CAMO_3", "WCT_CAMO_4", "WCT_CAMO_5", "WCT_CAMO_6", "WCT_CAMO_7", "WCT_CAMO_8", "WCT_CAMO_9", "WCT_CAMO_10", "WCT_CAMO_IND" };
const std::vector<std::string> VALUES_ATTACH_ASSAULTRIFLEMK2{ "COMPONENT_ASSAULTRIFLE_MK2_CLIP_01", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_02", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_TRACER", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_INCENDIARY", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_ARMORPIERCING", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_FMJ", "COMPONENT_AT_AR_AFGRIP_02", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SIGHTS", "COMPONENT_AT_SCOPE_MACRO_MK2", "COMPONENT_AT_SCOPE_MEDIUM_MK2", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_AT_MUZZLE_01", "COMPONENT_AT_MUZZLE_02", "COMPONENT_AT_MUZZLE_03", "COMPONENT_AT_MUZZLE_04", "COMPONENT_AT_MUZZLE_05", "COMPONENT_AT_MUZZLE_06", "COMPONENT_AT_MUZZLE_07", "COMPONENT_AT_AR_BARREL_01", "COMPONENT_AT_AR_BARREL_02", "COMPONENT_ASSAULTRIFLE_MK2_CAMO", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_02", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_03", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_04", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_05", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_06", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_07", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_08", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_09", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_10", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_IND_01" };

const std::vector<std::string> CAPTIONS_ATTACH_CARBINERIFLEMK2{ "WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_TR", "WCT_CLIP_INC", "WCT_CLIP_AP", "WCT_CLIP_FMJ", "WCT_GRIP", "WCT_FLASH", "WCT_HOLO", "WCT_SCOPE_MAC2", "WCT_SCOPE_MED2", "WCT_SUPP", "WCT_MUZZ1", "WCT_MUZZ2", "WCT_MUZZ3", "WCT_MUZZ4", "WCT_MUZZ5", "WCT_MUZZ6", "WCT_MUZZ7", "WCT_BARR", "WCT_BARR2", "WCT_CAMO_1", "WCT_CAMO_2", "WCT_CAMO_3", "WCT_CAMO_4", "WCT_CAMO_5", "WCT_CAMO_6", "WCT_CAMO_7", "WCT_CAMO_8", "WCT_CAMO_9", "WCT_CAMO_10", "WCT_CAMO_IND" };
const std::vector<std::string> VALUES_ATTACH_CARBINERIFLEMK2{ "COMPONENT_CARBINERIFLE_MK2_CLIP_01", "COMPONENT_CARBINERIFLE_MK2_CLIP_02", "COMPONENT_CARBINERIFLE_MK2_CLIP_TRACER", "COMPONENT_CARBINERIFLE_MK2_CLIP_INCENDIARY", "COMPONENT_CARBINERIFLE_MK2_CLIP_ARMORPIERCING", "COMPONENT_CARBINERIFLE_MK2_CLIP_FMJ", "COMPONENT_AT_AR_AFGRIP_02", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SIGHTS", "COMPONENT_AT_SCOPE_MACRO_MK2", "COMPONENT_AT_SCOPE_MEDIUM_MK2", "COMPONENT_AT_AR_SUPP", "COMPONENT_AT_MUZZLE_01", "COMPONENT_AT_MUZZLE_02", "COMPONENT_AT_MUZZLE_03", "COMPONENT_AT_MUZZLE_04", "COMPONENT_AT_MUZZLE_05", "COMPONENT_AT_MUZZLE_06", "COMPONENT_AT_MUZZLE_07", "COMPONENT_AT_CR_BARREL_01", "COMPONENT_AT_CR_BARREL_02", "COMPONENT_CARBINERIFLE_MK2_CAMO", "COMPONENT_CARBINERIFLE_MK2_CAMO_02", "COMPONENT_CARBINERIFLE_MK2_CAMO_03", "COMPONENT_CARBINERIFLE_MK2_CAMO_04", "COMPONENT_CARBINERIFLE_MK2_CAMO_05", "COMPONENT_CARBINERIFLE_MK2_CAMO_06", "COMPONENT_CARBINERIFLE_MK2_CAMO_07", "COMPONENT_CARBINERIFLE_MK2_CAMO_08", "COMPONENT_CARBINERIFLE_MK2_CAMO_09", "COMPONENT_CARBINERIFLE_MK2_CAMO_10", "COMPONENT_CARBINERIFLE_MK2_CAMO_IND_01" };

const std::vector<std::string> CAPTIONS_ATTACH_COMBATMGMK2{ "WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_TR", "WCT_CLIP_INC", "WCT_CLIP_AP", "WCT_CLIP_FMJ", "WCT_GRIP", "WCT_HOLO", "WCT_SCOPE_SML2", "WCT_SCOPE_MED2", "WCT_MUZZ1", "WCT_MUZZ2", "WCT_MUZZ3", "WCT_MUZZ4", "WCT_MUZZ5", "WCT_MUZZ6", "WCT_MUZZ7", "WCT_BARR", "WCT_BARR2", "WCT_CAMO_1", "WCT_CAMO_2", "WCT_CAMO_3", "WCT_CAMO_4", "WCT_CAMO_5", "WCT_CAMO_6", "WCT_CAMO_7", "WCT_CAMO_8", "WCT_CAMO_9", "WCT_CAMO_10", "WCT_CAMO_IND" };
const std::vector<std::string> VALUES_ATTACH_COMBATMGMK2{ "COMPONENT_COMBATMG_MK2_CLIP_01", "COMPONENT_COMBATMG_MK2_CLIP_02", "COMPONENT_COMBATMG_MK2_CLIP_TRACER", "COMPONENT_COMBATMG_MK2_CLIP_INCENDIARY", "COMPONENT_COMBATMG_MK2_CLIP_ARMORPIERCING", "COMPONENT_COMBATMG_MK2_CLIP_FMJ", "COMPONENT_AT_AR_AFGRIP_02", "COMPONENT_AT_SIGHTS", "COMPONENT_AT_SCOPE_SMALL_MK2", "COMPONENT_AT_SCOPE_MEDIUM_MK2", "COMPONENT_AT_MUZZLE_01", "COMPONENT_AT_MUZZLE_02", "COMPONENT_AT_MUZZLE_03", "COMPONENT_AT_MUZZLE_04", "COMPONENT_AT_MUZZLE_05", "COMPONENT_AT_MUZZLE_06", "COMPONENT_AT_MUZZLE_07", "COMPONENT_AT_MG_BARREL_01", "COMPONENT_AT_MG_BARREL_02", "COMPONENT_COMBATMG_MK2_CAMO", "COMPONENT_COMBATMG_MK2_CAMO_02", "COMPONENT_COMBATMG_MK2_CAMO_03", "COMPONENT_COMBATMG_MK2_CAMO_04", "COMPONENT_COMBATMG_MK2_CAMO_05", "COMPONENT_COMBATMG_MK2_CAMO_06", "COMPONENT_COMBATMG_MK2_CAMO_07", "COMPONENT_COMBATMG_MK2_CAMO_08", "COMPONENT_COMBATMG_MK2_CAMO_09", "COMPONENT_COMBATMG_MK2_CAMO_10", "COMPONENT_COMBATMG_MK2_CAMO_IND_01" };

const std::vector<std::string> CAPTIONS_ATTACH_HEAVYSNIPERMK2{ "WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_INC", "WCT_CLIP_AP", "WCT_CLIP_FMJ", "WCT_CLIP_EX", "WCT_SCOPE_LRG2", "WCT_SCOPE_MAX", "WCT_SCOPE_NV", "WCT_SCOPE_TH", "WCT_SUPP", "WCT_MUZZ8", "WCT_MUZZ9", "WCT_BARR", "WCT_BARR2", "WCT_CAMO_1", "WCT_CAMO_2", "WCT_CAMO_3", "WCT_CAMO_4", "WCT_CAMO_5", "WCT_CAMO_6", "WCT_CAMO_7", "WCT_CAMO_8", "WCT_CAMO_9", "WCT_CAMO_10", "WCT_CAMO_IND" };
const std::vector<std::string> VALUES_ATTACH_HEAVYSNIPERMK2{ "COMPONENT_HEAVYSNIPER_MK2_CLIP_01", "COMPONENT_HEAVYSNIPER_MK2_CLIP_02", "COMPONENT_HEAVYSNIPER_MK2_CLIP_INCENDIARY", "COMPONENT_HEAVYSNIPER_MK2_CLIP_ARMORPIERCING", "COMPONENT_HEAVYSNIPER_MK2_CLIP_FMJ", "COMPONENT_HEAVYSNIPER_MK2_CLIP_EXPLOSIVE", "COMPONENT_AT_SCOPE_LARGE_MK2", "COMPONENT_AT_SCOPE_MAX", "COMPONENT_AT_SCOPE_NV", "COMPONENT_AT_SCOPE_THERMAL", "COMPONENT_AT_SR_SUPP_03", "COMPONENT_AT_MUZZLE_08", "COMPONENT_AT_MUZZLE_09", "COMPONENT_AT_SR_BARREL_01", "COMPONENT_AT_SR_BARREL_02", "COMPONENT_HEAVYSNIPER_MK2_CAMO", "COMPONENT_HEAVYSNIPER_MK2_CAMO_02", "COMPONENT_HEAVYSNIPER_MK2_CAMO_03", "COMPONENT_HEAVYSNIPER_MK2_CAMO_04", "COMPONENT_HEAVYSNIPER_MK2_CAMO_05", "COMPONENT_HEAVYSNIPER_MK2_CAMO_06", "COMPONENT_HEAVYSNIPER_MK2_CAMO_07", "COMPONENT_HEAVYSNIPER_MK2_CAMO_08", "COMPONENT_HEAVYSNIPER_MK2_CAMO_09", "COMPONENT_HEAVYSNIPER_MK2_CAMO_10", "COMPONENT_HEAVYSNIPER_MK2_CAMO_IND_01" };

/* 末日豪劫 */
const std::vector<std::string> CAPTIONS_ATTACH_SNSPISTOLMK2{ "WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_TR", "WCT_CLIP_INC", "WCT_CLIP_HP", "WCT_CLIP_FMJ", "WCT_FLASH", "WCT_SCOPE_PI", "WCT_SUPP", "WCT_COMP", "WCT_CAMO_1", "WCT_CAMO_2", "WCT_CAMO_3", "WCT_CAMO_4", "WCT_CAMO_5", "WCT_CAMO_6", "WCT_CAMO_7", "WCT_CAMO_8", "WCT_CAMO_9", "WCT_CAMO_10", "WCT_CAMO_IND", "WCT_CAMO_1", "WCT_CAMO_2", "WCT_CAMO_3", "WCT_CAMO_4", "WCT_CAMO_5", "WCT_CAMO_6", "WCT_CAMO_7", "WCT_CAMO_8", "WCT_CAMO_9", "WCT_CAMO_10", "WCT_CAMO_IND" };
const std::vector<std::string> VALUES_ATTACH_SNSPISTOLMK2{ "COMPONENT_SNSPISTOL_MK2_CLIP_01", "COMPONENT_SNSPISTOL_MK2_CLIP_02", "COMPONENT_SNSPISTOL_MK2_CLIP_TRACER", "COMPONENT_SNSPISTOL_MK2_CLIP_INCENDIARY", "COMPONENT_SNSPISTOL_MK2_CLIP_HOLLOWPOINT", "COMPONENT_SNSPISTOL_MK2_CLIP_FMJ", "COMPONENT_AT_PI_FLSH_03", "COMPONENT_AT_PI_RAIL_02", "COMPONENT_AT_PI_SUPP_02", "COMPONENT_AT_PI_COMP_02", "COMPONENT_SNSPISTOL_MK2_CAMO", "COMPONENT_SNSPISTOL_MK2_CAMO_02", "COMPONENT_SNSPISTOL_MK2_CAMO_03", "COMPONENT_SNSPISTOL_MK2_CAMO_04", "COMPONENT_SNSPISTOL_MK2_CAMO_05", "COMPONENT_SNSPISTOL_MK2_CAMO_06", "COMPONENT_SNSPISTOL_MK2_CAMO_07", "COMPONENT_SNSPISTOL_MK2_CAMO_08", "COMPONENT_SNSPISTOL_MK2_CAMO_09", "COMPONENT_SNSPISTOL_MK2_CAMO_10", "COMPONENT_SNSPISTOL_MK2_CAMO_IND_01", "COMPONENT_SNSPISTOL_MK2_CAMO_SLIDE", "COMPONENT_SNSPISTOL_MK2_CAMO_02_SLIDE", "COMPONENT_SNSPISTOL_MK2_CAMO_03_SLIDE", "COMPONENT_SNSPISTOL_MK2_CAMO_04_SLIDE", "COMPONENT_SNSPISTOL_MK2_CAMO_05_SLIDE", "COMPONENT_SNSPISTOL_MK2_CAMO_06_SLIDE", "COMPONENT_SNSPISTOL_MK2_CAMO_07_SLIDE", "COMPONENT_SNSPISTOL_MK2_CAMO_08_SLIDE", "COMPONENT_SNSPISTOL_MK2_CAMO_09_SLIDE", "COMPONENT_SNSPISTOL_MK2_CAMO_10_SLIDE", "COMPONENT_SNSPISTOL_MK2_CAMO_IND_01_SLIDE" };

const std::vector<std::string> CAPTIONS_ATTACH_REVOLVERMK2{ "WCT_CLIP1_RV", "WCT_CLIP_TR", "WCT_CLIP_INC", "WCT_CLIP_HP", "WCT_CLIP_FMJ", "WCT_HOLO", "WCT_SCOPE_MAC2", "WCT_FLASH", "WCT_COMP", "WCT_CAMO_1", "WCT_CAMO_2", "WCT_CAMO_3", "WCT_CAMO_4", "WCT_CAMO_5", "WCT_CAMO_6", "WCT_CAMO_7", "WCT_CAMO_8", "WCT_CAMO_9", "WCT_CAMO_10", "WCT_CAMO_IND" };
const std::vector<std::string> VALUES_ATTACH_REVOLVERMK2{ "COMPONENT_REVOLVER_MK2_CLIP_01", "COMPONENT_REVOLVER_MK2_CLIP_TRACER", "COMPONENT_REVOLVER_MK2_CLIP_INCENDIARY", "COMPONENT_REVOLVER_MK2_CLIP_HOLLOWPOINT", "COMPONENT_REVOLVER_MK2_CLIP_FMJ", "COMPONENT_AT_SIGHTS", "COMPONENT_AT_SCOPE_MACRO_MK2", "COMPONENT_AT_PI_FLSH", "COMPONENT_AT_PI_COMP_03", "COMPONENT_REVOLVER_MK2_CAMO", "COMPONENT_REVOLVER_MK2_CAMO_02", "COMPONENT_REVOLVER_MK2_CAMO_03", "COMPONENT_REVOLVER_MK2_CAMO_04", "COMPONENT_REVOLVER_MK2_CAMO_05", "COMPONENT_REVOLVER_MK2_CAMO_06", "COMPONENT_REVOLVER_MK2_CAMO_07", "COMPONENT_REVOLVER_MK2_CAMO_08", "COMPONENT_REVOLVER_MK2_CAMO_09", "COMPONENT_REVOLVER_MK2_CAMO_10", "COMPONENT_REVOLVER_MK2_CAMO_IND_01" };

const std::vector<std::string> CAPTIONS_ATTACH_SPECIALCARBINEMK2{ "WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_TR", "WCT_CLIP_INC", "WCT_CLIP_AP", "WCT_CLIP_FMJ", "WCT_FLASH", "WCT_HOLO", "WCT_SCOPE_MAC2", "WCT_SCOPE_MED2", "WCT_SUPP", "WCT_MUZZ1", "WCT_MUZZ2", "WCT_MUZZ3", "WCT_MUZZ4", "WCT_MUZZ5", "WCT_MUZZ6", "WCT_MUZZ7", "WCT_GRIP", "WCT_BARR", "WCT_BARR2", "WCT_CAMO_1", "WCT_CAMO_2", "WCT_CAMO_3", "WCT_CAMO_4", "WCT_CAMO_5", "WCT_CAMO_6", "WCT_CAMO_7", "WCT_CAMO_8", "WCT_CAMO_9", "WCT_CAMO_10", "WCT_CAMO_IND" };
const std::vector<std::string> VALUES_ATTACH_SPECIALCARBINEMK2{ "COMPONENT_SPECIALCARBINE_MK2_CLIP_01", "COMPONENT_SPECIALCARBINE_MK2_CLIP_02", "COMPONENT_SPECIALCARBINE_MK2_CLIP_TRACER", "COMPONENT_SPECIALCARBINE_MK2_CLIP_INCENDIARY", "COMPONENT_SPECIALCARBINE_MK2_CLIP_ARMORPIERCING", "COMPONENT_SPECIALCARBINE_MK2_CLIP_FMJ", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SIGHTS", "COMPONENT_AT_SCOPE_MACRO_MK2", "COMPONENT_AT_SCOPE_MEDIUM_MK2", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_AT_MUZZLE_01", "COMPONENT_AT_MUZZLE_02", "COMPONENT_AT_MUZZLE_03", "COMPONENT_AT_MUZZLE_04", "COMPONENT_AT_MUZZLE_05", "COMPONENT_AT_MUZZLE_06", "COMPONENT_AT_MUZZLE_07", "COMPONENT_AT_AR_AFGRIP_02", "COMPONENT_AT_SC_BARREL_01", "COMPONENT_AT_SC_BARREL_02", "COMPONENT_SPECIALCARBINE_MK2_CAMO", "COMPONENT_SPECIALCARBINE_MK2_CAMO_02", "COMPONENT_SPECIALCARBINE_MK2_CAMO_03", "COMPONENT_SPECIALCARBINE_MK2_CAMO_04", "COMPONENT_SPECIALCARBINE_MK2_CAMO_05", "COMPONENT_SPECIALCARBINE_MK2_CAMO_06", "COMPONENT_SPECIALCARBINE_MK2_CAMO_07", "COMPONENT_SPECIALCARBINE_MK2_CAMO_08", "COMPONENT_SPECIALCARBINE_MK2_CAMO_09", "COMPONENT_SPECIALCARBINE_MK2_CAMO_10", "COMPONENT_SPECIALCARBINE_MK2_CAMO_IND_01" };

const std::vector<std::string> CAPTIONS_ATTACH_BULLPUPMK2{ "WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_TR", "WCT_CLIP_INC", "WCT_CLIP_AP", "WCT_CLIP_FMJ", "WCT_FLASH", "WCT_HOLO", "WCT_SCOPE_MAC2", "WCT_SCOPE_SML2", "WCT_BARR", "WCT_BARR2", "WCT_SUPP", "WCT_MUZZ1", "WCT_MUZZ2", "WCT_MUZZ3", "WCT_MUZZ4", "WCT_MUZZ5", "WCT_MUZZ6", "WCT_MUZZ7", "WCT_GRIP", "WCT_CAMO_1", "WCT_CAMO_2", "WCT_CAMO_3", "WCT_CAMO_4", "WCT_CAMO_5", "WCT_CAMO_6", "WCT_CAMO_7", "WCT_CAMO_8", "WCT_CAMO_9", "WCT_CAMO_10", "WCT_CAMO_IND" };
const std::vector<std::string> VALUES_ATTACH_BULLPUPMK2{ "COMPONENT_BULLPUPRIFLE_MK2_CLIP_01", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_02", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_TRACER", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_INCENDIARY", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_ARMORPIERCING", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_FMJ", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SIGHTS", "COMPONENT_AT_SCOPE_MACRO_02_MK2", "COMPONENT_AT_SCOPE_SMALL_MK2", "COMPONENT_AT_BP_BARREL_01", "COMPONENT_AT_BP_BARREL_02", "COMPONENT_AT_AR_SUPP", "COMPONENT_AT_MUZZLE_01", "COMPONENT_AT_MUZZLE_02", "COMPONENT_AT_MUZZLE_03", "COMPONENT_AT_MUZZLE_04","COMPONENT_AT_MUZZLE_05","COMPONENT_AT_MUZZLE_06","COMPONENT_AT_MUZZLE_07","COMPONENT_AT_AR_AFGRIP_02","COMPONENT_BULLPUPRIFLE_MK2_CAMO","COMPONENT_BULLPUPRIFLE_MK2_CAMO_02","COMPONENT_BULLPUPRIFLE_MK2_CAMO_03","COMPONENT_BULLPUPRIFLE_MK2_CAMO_04","COMPONENT_BULLPUPRIFLE_MK2_CAMO_05", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_06", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_07", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_08", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_09", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_10", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_IND_01" };

const std::vector<std::string> CAPTIONS_ATTACH_PUMPSHOTGUNMK2{ "WCT_SHELL", "WCT_SHELL_INC", "WCT_SHELL_AP", "WCT_SHELL_HP", "WCT_SHELL_EX", "WCT_HOLO", "WCT_SCOPE_MAC2", "WCT_SCOPE_SML2", "WCT_FLASH", "WCT_SUPP", "WCT_MUZZ", "WCT_CAMO_1", "WCT_CAMO_2", "WCT_CAMO_3", "WCT_CAMO_4", "WCT_CAMO_5", "WCT_CAMO_6", "WCT_CAMO_7", "WCT_CAMO_8", "WCT_CAMO_9", "WCT_CAMO_10", "WCT_CAMO_IND" };
const std::vector<std::string> VALUES_ATTACH_PUMPSHOTGUNMK2{ "COMPONENT_PUMPSHOTGUN_MK2_CLIP_01", "COMPONENT_PUMPSHOTGUN_MK2_CLIP_INCENDIARY", "COMPONENT_PUMPSHOTGUN_MK2_CLIP_ARMORPIERCING", "COMPONENT_PUMPSHOTGUN_MK2_CLIP_HOLLOWPOINT", "COMPONENT_PUMPSHOTGUN_MK2_CLIP_EXPLOSIVE", "COMPONENT_AT_SIGHTS", "COMPONENT_AT_SCOPE_MACRO_MK2", "COMPONENT_AT_SCOPE_SMALL_MK2", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_SR_SUPP_03", "COMPONENT_AT_MUZZLE_08", "COMPONENT_PUMPSHOTGUN_MK2_CAMO", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_02", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_03", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_04", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_05", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_06", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_07", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_08", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_09", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_10", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_IND_01" };

const std::vector<std::string> CAPTIONS_ATTACH_MARKSMANRIFLEMK2{ "WCT_CLIP1", "WCT_CLIP2", "WCT_CLIP_TR", "WCT_CLIP_INC", "WCT_CLIP_AP", "WCT_CLIP_FMJ", "WCT_HOLO", "WCT_SCOPE_MED2", "WCT_SCOPE_LRG2", "WCT_FLASH", "WCT_SUPP", "WCT_MUZZ1", "WCT_MUZZ2", "WCT_MUZZ3", "WCT_MUZZ4", "WCT_MUZZ5", "WCT_MUZZ6", "WCT_MUZZ7", "WCT_BARR", "WCT_BARR2", "WCT_GRIP", "WCT_CAMO_1", "WCT_CAMO_2", "WCT_CAMO_3", "WCT_CAMO_4", "WCT_CAMO_5", "WCT_CAMO_6", "WCT_CAMO_7", "WCT_CAMO_8", "WCT_CAMO_9", "WCT_CAMO_10", "WCT_CAMO_IND" };
const std::vector<std::string> VALUES_ATTACH_MARKSMANRIFLEMK2{ "COMPONENT_MARKSMANRIFLE_MK2_CLIP_01", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_02", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_TRACER", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_INCENDIARY", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_ARMORPIERCING", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_FMJ", "COMPONENT_AT_SIGHTS", "COMPONENT_AT_SCOPE_MEDIUM_MK2", "COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM_MK2", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_AR_SUPP", "COMPONENT_AT_MUZZLE_01", "COMPONENT_AT_MUZZLE_02", "COMPONENT_AT_MUZZLE_03", "COMPONENT_AT_MUZZLE_04", "COMPONENT_AT_MUZZLE_05", "COMPONENT_AT_MUZZLE_06", "COMPONENT_AT_MUZZLE_07", "COMPONENT_AT_MRFL_BARREL_01", "COMPONENT_AT_MRFL_BARREL_02", "COMPONENT_AT_AR_AFGRIP_02", "COMPONENT_MARKSMANRIFLE_MK2_CAMO", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_02", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_03", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_04", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_05", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_06", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_07", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_08", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_09", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_10", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_IND_01" };

const std::vector<std::string> CAPTIONS_ATTACH_CERAMIC_PISTOL{ "WCT_CLIP1", "WCT_CLIP2", "WCT_SUPP" };
const std::vector<std::string> VALUES_ATTACH_CERAMIC_PISTOL{ "COMPONENT_CERAMICPISTOL_CLIP_01", "COMPONENT_CERAMICPISTOL_CLIP_02", "COMPONENT_CERAMICPISTOL_SUPP" };

// 射线手枪
const std::vector<std::string> CAPTIONS_ATTACH_RAY_PISTOL{ "WCT_VAR_RAY18" };
const std::vector<std::string> VALUES_ATTACH_RAY_PISTOL{ "COMPONENT_RAYPISTOL_VARMOD_XMAS18" };

// 佩里科岛劫案
const std::vector<std::string> CAPTIONS_ATTACH_MILITARYRIFLE{ "WCT_CLIP1", "WCT_CLIP2", "WCT_MRFL_SIGHT", "WCT_SCOPE_SML", "WCT_FLASH", "WCT_SUPP" };
const std::vector<std::string> VALUES_ATTACH_MILITARYRIFLE{ "COMPONENT_MILITARYRIFLE_CLIP_01", "COMPONENT_MILITARYRIFLE_CLIP_02", "COMPONENT_MILITARYRIFLE_SIGHT_01", "COMPONENT_AT_SCOPE_SMALL", "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_AR_SUPP" };

const std::vector<std::string> CAPTIONS_ATTACH_COMBATSHOTGUN{ "WCT_FLASH", "WCT_SUPP" };
const std::vector<std::string> VALUES_ATTACH_COMBATSHOTGUN{ "COMPONENT_AT_AR_FLSH", "COMPONENT_AT_AR_SUPP" };

// 事务所 DLC
const std::vector<std::string> CAPTIONS_ATTACH_TACTICALRIFLE{ "WCT_FLASH", "WCT_CLIP2", "WCT_SUPP", "WCT_GRIP" };
const std::vector<std::string> VALUES_ATTACH_TACTICALRIFLE{ "COMPONENT_AT_AR_FLSH_REH", "COMPONENT_TACTICALRIFLE_CLIP_02", "COMPONENT_AT_AR_SUPP_02", "COMPONENT_AT_AR_AFGRIP" };

// 2022 圣诞 DLC
const std::vector<std::string> CAPTIONS_ATTACH_PISTOLXM3{ "WCT_CLIP1", "WCT_SUPP"};
const std::vector<std::string> VALUES_ATTACH_PISTOLXM3{"COMPONENT_PISTOLXM3_CLIP_01", "COMPONENT_PISTOLXM3_SUPP" };

// 2023 圣诞 DLC
const std::vector<std::string> CAPTIONS_ATTACH_BATTLERIFLE{ "WCT_CLIP1", "WCT_CLIP2", "WCT_SUPP"};
const std::vector<std::string> VALUES_ATTACH_BATTLERIFLE{ "COMPONENT_BATTLERIFLE_CLIP_01", "COMPONENT_BATTLERIFLE_CLIP_02", "COMPONENT_AT_AR_SUPP"};

// 可涂装武器列表
const std::vector<std::string> WEAPONTYPES_TINT{ "WEAPON_PISTOL", "WEAPON_COMBATPISTOL", "WEAPON_APPISTOL", "WEAPON_PISTOL50", "WEAPON_SNSPISTOL", "WEAPON_HEAVYPISTOL", "WEAPON_VINTAGEPISTOL", "WEAPON_STUNGUN", "WEAPON_FLAREGUN", "WEAPON_MARKSMANPISTOL", "WEAPON_MICROSMG", "WEAPON_SMG", "WEAPON_ASSAULTSMG", "WEAPON_MG", "WEAPON_COMBATMG", "WEAPON_GUSENBERG", "WEAPON_ASSAULTRIFLE", "WEAPON_CARBINERIFLE", "WEAPON_ADVANCEDRIFLE", "WEAPON_SPECIALCARBINE", "WEAPON_BULLPUPRIFLE", "WEAPON_PUMPSHOTGUN", "WEAPON_SAWNOFFSHOTGUN", "WEAPON_BULLPUPSHOTGUN", "WEAPON_ASSAULTSHOTGUN", "WEAPON_MUSKET", "WEAPON_HEAVYSHOTGUN", "WEAPON_SNIPERRIFLE", "WEAPON_HEAVYSNIPER", "WEAPON_MARKSMANRIFLE", "WEAPON_GRENADELAUNCHER", "WEAPON_RPG", "WEAPON_MINIGUN", "WEAPON_FIREWORK", "WEAPON_RAILGUN", "WEAPON_HOMINGLAUNCHER", "WEAPON_COMBATPDW", "WEAPON_MACHINEPISTOL", "WEAPON_DBSHOTGUN", "WEAPON_COMPACTRIFLE", "WEAPON_AUTOSHOTGUN", "WEAPON_COMPACTLAUNCHER", "WEAPON_MINISMG", "WEAPON_PISTOL_MK2", "WEAPON_SMG_MK2", "WEAPON_ASSAULTRIFLE_MK2", "WEAPON_CARBINERIFLE_MK2", "WEAPON_COMBATMG_MK2", "WEAPON_HEAVYSNIPER_MK2", /*"WEAPON_SNSPISTOL_MK2", "WEAPON_REVOLVER_MK2", "WEAPON_SPECIALCARBINE_MK2", "WEAPON_BULLPUPRIFLE_MK2", "WEAPON_PUMPSHOTGUN_MK2", "WEAPON_MARKSMANRIFLE_MK2", WEAPON_DOUBLEACTION*/ "WEAPON_RAYPISTOL", "WEAPON_RAYCARBINE", "WEAPON_RAYMINIGUN", "WEAPON_TACTICALRIFLE", "WEAPON_PRECISIONRIFLE", "WEAPON_TECPISTOL", "WEAPON_BATTLERIFLE"};

// 可改装武器列表
const std::vector<std::string> WEAPONTYPES_MOD{ "WEAPON_PISTOL", "WEAPON_HEAVYPISTOL", "WEAPON_COMBATPISTOL", "WEAPON_APPISTOL", "WEAPON_PISTOL50", "WEAPON_MICROSMG", "WEAPON_SMG", "WEAPON_ASSAULTSMG", "WEAPON_ASSAULTRIFLE", "WEAPON_CARBINERIFLE", "WEAPON_ADVANCEDRIFLE", "WEAPON_MG", "WEAPON_COMBATMG", "WEAPON_SAWNOFFSHOTGUN", "WEAPON_PUMPSHOTGUN", "WEAPON_ASSAULTSHOTGUN", "WEAPON_BULLPUPSHOTGUN", "WEAPON_SNIPERRIFLE", "WEAPON_HEAVYSNIPER", "WEAPON_GRENADELAUNCHER", "WEAPON_BULLPUPRIFLE", "WEAPON_GUSENBERG", "WEAPON_HEAVYSHOTGUN", "WEAPON_MARKSMANRIFLE", "WEAPON_SNSPISTOL", "WEAPON_SPECIALCARBINE", "WEAPON_VINTAGEPISTOL", "WEAPON_COMBATPDW", "WEAPON_MACHINEPISTOL", "WEAPON_SWITCHBLADE", "WEAPON_REVOLVER", "WEAPON_COMPACTRIFLE", "WEAPON_MINISMG", "WEAPON_PISTOL_MK2", "WEAPON_SMG_MK2", "WEAPON_ASSAULTRIFLE_MK2", "WEAPON_CARBINERIFLE_MK2", "WEAPON_COMBATMG_MK2", "WEAPON_HEAVYSNIPER_MK2", "WEAPON_SNSPISTOL_MK2", "WEAPON_REVOLVER_MK2", "WEAPON_SPECIALCARBINE_MK2", "WEAPON_BULLPUPRIFLE_MK2", "WEAPON_PUMPSHOTGUN_MK2", "WEAPON_MARKSMANRIFLE_MK2", "WEAPON_CERAMICPISTOL", "WEAPON_MILITARYRIFLE", "WEAPON_COMBATSHOTGUN", "WEAPON_HEAVYRIFLE", "WEAPON_TACTICALRIFLE", "WEAPON_PISTOLXM3", "WEAPON_TECPISTOL", "WEAPON_BATTLERIFLE"};

const std::vector<std::string> VOV_WEAPONMOD_CAPTIONS[] = { CAPTIONS_ATTACH_PISTOL, CAPTIONS_ATTACH_HEAVYPISTOL, CAPTIONS_ATTACH_COMBATPISTOL, CAPTIONS_ATTACH_APPISTOL, CAPTIONS_ATTACH_PISTOL50, CAPTIONS_ATTACH_MICROSMG, CAPTIONS_ATTACH_SMG, CAPTIONS_ATTACH_ASSAULTSMG, CAPTIONS_ATTACH_ASSAULTRIFLE, CAPTIONS_ATTACH_CARBINERIFLE, CAPTIONS_ATTACH_ADVANCEDRIFLE, CAPTIONS_ATTACH_MG, CAPTIONS_ATTACH_COMBATMG, CAPTIONS_ATTACH_SAWNOFF, CAPTIONS_ATTACH_PUMPSHOTGUN, CAPTIONS_ATTACH_ASSAULTSHOTGUN, CAPTIONS_ATTACH_BULLPUPSHOTGUN, CAPTIONS_ATTACH_SNIPERRIFLE, CAPTIONS_ATTACH_HEAVYSNIPER, CAPTIONS_ATTACH_GRENADELAUNCHER, CAPTIONS_ATTACH_BULLPUPRIFLE, CAPTIONS_ATTACH_GUSENBERG, CAPTIONS_ATTACH_HEAVYSHOTGUN, CAPTIONS_ATTACH_MARKSMANRIFLE, CAPTIONS_ATTACH_SNSPISTOL, CAPTIONS_ATTACH_SPECIALCARBINE, CAPTIONS_ATTACH_VINTAGEPISTOL, CAPTIONS_ATTACH_COMBATPDW, CAPTIONS_ATTACH_MACHINEPISTOL, CAPTIONS_ATTACH_SWITCHBLADE, CAPTIONS_ATTACH_REVOLVER, CAPTIONS_ATTACH_COMPACTRIFLE, CAPTIONS_ATTACH_MINISMG, CAPTIONS_ATTACH_PISTOLMK2, CAPTIONS_ATTACH_SMGMK2, CAPTIONS_ATTACH_ASSAULTRIFLEMK2, CAPTIONS_ATTACH_CARBINERIFLEMK2, CAPTIONS_ATTACH_COMBATMGMK2, CAPTIONS_ATTACH_HEAVYSNIPERMK2, CAPTIONS_ATTACH_SNSPISTOLMK2, CAPTIONS_ATTACH_REVOLVERMK2, CAPTIONS_ATTACH_SPECIALCARBINEMK2, CAPTIONS_ATTACH_BULLPUPMK2, CAPTIONS_ATTACH_PUMPSHOTGUNMK2, CAPTIONS_ATTACH_MARKSMANRIFLEMK2, /*CAPTIONS_ATTACH_RAY_PISTOL,*/ CAPTIONS_ATTACH_CERAMIC_PISTOL, CAPTIONS_ATTACH_MILITARYRIFLE, CAPTIONS_ATTACH_COMBATSHOTGUN, CAPTIONS_ATTACH_HEAVYRIFLE, CAPTIONS_ATTACH_TACTICALRIFLE, CAPTIONS_ATTACH_PISTOLXM3, CAPTIONS_ATTACH_WEAPON_TECPISTOL, CAPTIONS_ATTACH_BATTLERIFLE };
const std::vector<std::string> VOV_WEAPONMOD_VALUES[] = { VALUES_ATTACH_PISTOL, VALUES_ATTACH_HEAVYPISTOL, VALUES_ATTACH_COMBATPISTOL, VALUES_ATTACH_APPISTOL, VALUES_ATTACH_PISTOL50, VALUES_ATTACH_MICROSMG, VALUES_ATTACH_SMG, VALUES_ATTACH_ASSAULTSMG, VALUES_ATTACH_ASSAULTRIFLE, VALUES_ATTACH_CARBINERIFLE, VALUES_ATTACH_ADVANCEDRIFLE, VALUES_ATTACH_MG, VALUES_ATTACH_COMBATMG, VALUES_ATTACH_SAWNOFF, VALUES_ATTACH_PUMPSHOTGUN, VALUES_ATTACH_ASSAULTSHOTGUN, VALUES_ATTACH_BULLPUPSHOTGUN, VALUES_ATTACH_SNIPERRIFLE, VALUES_ATTACH_HEAVYSNIPER, VALUES_ATTACH_GRENADELAUNCHER, VALUES_ATTACH_BULLPUPRIFLE, VALUES_ATTACH_GUSENBERG, VALUES_ATTACH_HEAVYSHOTGUN, VALUES_ATTACH_MARKSMANRIFLE, VALUES_ATTACH_SNSPISTOL, VALUES_ATTACH_SPECIALCARBINE, VALUES_ATTACH_VINTAGEPISTOL, VALUES_ATTACH_COMBATPDW, VALUES_ATTACH_MACHINEPISTOL, VALUES_ATTACH_SWITCHBLADE, VALUES_ATTACH_REVOLVER, VALUES_ATTACH_COMPACTRIFLE, VALUES_ATTACH_MINISMG, VALUES_ATTACH_PISTOLMK2, VALUES_ATTACH_SMGMK2, VALUES_ATTACH_ASSAULTRIFLEMK2, VALUES_ATTACH_CARBINERIFLEMK2, VALUES_ATTACH_COMBATMGMK2, VALUES_ATTACH_HEAVYSNIPERMK2, VALUES_ATTACH_SNSPISTOLMK2, VALUES_ATTACH_REVOLVERMK2, VALUES_ATTACH_SPECIALCARBINEMK2, VALUES_ATTACH_BULLPUPMK2, VALUES_ATTACH_PUMPSHOTGUNMK2, VALUES_ATTACH_MARKSMANRIFLEMK2, /*VALUES_ATTACH_RAY_PISTOL,*/ VALUES_ATTACH_CERAMIC_PISTOL, VALUES_ATTACH_MILITARYRIFLE, VALUES_ATTACH_COMBATSHOTGUN, VALUES_ATTACH_HEAVYRIFLE, VALUES_ATTACH_TACTICALRIFLE, VALUES_ATTACH_PISTOLXM3, VALUES_ATTACH_WEAPON_TECPISTOL, VALUES_ATTACH_BATTLERIFLE };

// MK2 武器
const std::vector<char*> MK2_WEAPONS{ "WEAPON_PISTOL_MK2", "WEAPON_SNSPISTOL_MK2", "WEAPON_REVOLVER_MK2", "WEAPON_SMG_MK2", "WEAPON_COMBATMG_MK2", "WEAPON_ASSAULTRIFLE_MK2", "WEAPON_BULLPUPRIFLE_MK2", "WEAPON_CARBINERIFLE_MK2", "WEAPON_SPECIALCARBINE_MK2", "WEAPON_PUMPSHOTGUN_MK2", "WEAPON_HEAVYSNIPER_MK2", "WEAPON_MARKSMANRIFLE_MK2" };
const std::vector<char*> MK2_WEAPONS_LIVERY_COMP{ "COMPONENT_PISTOL_MK2_CAMO", "COMPONENT_SNSPISTOL_MK2_CAMO", "COMPONENT_REVOLVER_MK2_CAMO", "COMPONENT_SMG_MK2_CAMO", "COMPONENT_COMBATMG_MK2_CAMO", "COMPONENT_ASSAULTRIFLE_MK2_CAMO", "COMPONENT_BULLPUPRIFLE_MK2_CAMO", "COMPONENT_CARBINERIFLE_MK2_CAMO", "COMPONENT_SPECIALCARBINE_MK2_CAMO", "COMPONENT_PUMPSHOTGUN_MK2_CAMO", "COMPONENT_HEAVYSNIPER_MK2_CAMO", "COMPONENT_MARKSMANRIFLE_MK2_CAMO" };

// 武器伤害修改列表
const std::vector<std::string> WEAP_DMG_CAPTIONS{ "1.0x", "1.5x", "2.0x", "3.0x", "5.0x", "10.0x", "50.0x", "100.0x", "1000.0x" };
const float WEAP_DMG_FLOAT[] = { 1.0, 1.5, 2.0, 3.0, 5.0, 10.0, 50.0, 100.0, 1000.0 };

const int PARACHUTE_ID = 0xFBAB5776;

const int TOTAL_WEAPONS_COUNT = 150;
const int MAX_MOD_SLOTS = 15; 

extern bool featureNightVision;
extern bool featureThermalVision;
extern int activeLineIndexPowerPunchWeapons;
const std::vector<std::string> WEAPONS_POWERPUNCH_CAPTIONS{ "1", "3", "5", "10", "50", "手动" };
const int WEAPONS_POWERPUNCH_VALUES[] = { 1, 3, 5, 10, 50, 55 };
extern int PowerPunchIndex;
extern bool featurePunchFists;
extern bool featurePunchMeleeWeapons;
extern bool featurePunchFireWeapons;
extern bool featurePowerPunch;
extern std::string lastPowerWeapon;

extern int tick_allw;

bool process_weapon_menu();

bool process_weaponlist_menu();

void reset_weapon_globals();

void update_weapon_features(BOOL bPlayerExists, Player player);

void onchange_cop_armed_index(int value, SelectFromListMenuItem* source);

void onchange_chance_police_calling_index(int value, SelectFromListMenuItem* source);

void onchange_chance_attacking_you_index(int value, SelectFromListMenuItem* source);

void onchange_power_punch_index(int value, SelectFromListMenuItem* source);

void onchange_weapons_firemode_modifier(int value, SelectFromListMenuItem* source);

void onchange_weapons_rapidfire_modifier(int value, SelectFromListMenuItem* source);

void onchange_weap_strobe_index(int value, SelectFromListMenuItem* source);

void onchange_weap_flashdist_index(int value, SelectFromListMenuItem* source);

void onchange_sniper_vision_modifier(int value, SelectFromListMenuItem* source);

void onchange_vehicle_weapon_modifier(int value, SelectFromListMenuItem* source);

void onchange_weapon_no_reticle_modifier(int value, SelectFromListMenuItem* source);

void onchange_weapon_load_saved_modifier(int value, SelectFromListMenuItem* source);

void onchange_cop_alarm_index(int value, SelectFromListMenuItem* source);

void add_weapon_feature_enablements2(std::vector<StringPairSettingDBRow>* results);

void save_player_weapons(Ped playerPed);

void give_all_weapons_hotkey();

void sniper_vision_toggle();

void restore_player_weapons(Ped playerPed);

bool is_weapon_equipped(std::vector<int> extras);

bool process_weapon_save_slot_menu(int slot);

void set_weapon_equipped(bool equipped, std::vector<int> extras);

bool is_weaponmod_equipped(std::vector<int> extras);

void set_weaponmod_equipped(bool equipped, std::vector<int> extras);

void give_weapon_clip(MenuItem<int> choice);

void fill_weapon_ammo(MenuItem<int> choice);

void onconfirm_open_tint_menu(MenuItem<int> choice);

Vector3 DirectionOffsetFromCam(float distance);

void VectorToFloat(Vector3 unk, float *Out);

Vector3 add(Vector3* vectorA, Vector3* vectorB);

// 武器模组菜单
bool onconfirm_weapon_mod_menu_tint(MenuItem<int> choice);

void add_weapon_feature_enablements(std::vector<FeatureEnabledLocalDefinition>* results);

bool weapon_reequip_interrupt();

void onhighlight_weapon_mod_menu_tint_colour(MenuItem<int> choice);

bool onconfirm_weapon_mod_menu_tint_colour(MenuItem<int> choice);

void onconfirm_open_tint_menu_colour(MenuItem<int> choice);

// 武器伤害修改器
void onchange_weap_dmg_modifier(int value, SelectFromListMenuItem* source);

void add_weapons_generic_settings(std::vector<StringPairSettingDBRow>* results);

void handle_generic_settings_weapons(std::vector<StringPairSettingDBRow>* settings);

void fire_mode_hotkey();

void add_all_weapons_attachments(Ped choice);

extern Ped equip_ped;

// 全局屏幕准星相关常量和变量
extern bool featureWeaponsCrosshair; // 屏幕准星开关

const std::vector<std::string> WEAPONS_CROSSHAIR_STYLE_CAPTIONS{"实线十字", "虚线十字", "空心方形", "实心方形"};
const int WEAPONS_CROSSHAIR_STYLE_VALUES[] = { 1, 2, 3, 4 }; // 1=实线,2=虚线,3=空心方块,4=实心方块

const std::vector<std::string> WEAPONS_CROSSHAIR_COLOR_CAPTIONS{ "白色", "红色", "粉红色", "绿色", "蓝色", "黄色", "橙色", "紫色", "黑色", "灰色" };
const int WEAPONS_CROSSHAIR_COLOR_COUNT = 10; // 颜色数量

extern int WeaponsCrosshairStyleIndex; // 默认1 实线
extern bool WeaponsCrosshairStyleChanged;
extern int WeaponsCrosshairColorIndex; // 默认0 白色
extern bool WeaponsCrosshairColorChanged;

// 屏幕准星相关函数声明
void draw_weapons_crosshair();
void onchange_weapons_crosshair_style_index(int value, SelectFromListMenuItem* source);
void onchange_weapons_crosshair_color_index(int value, SelectFromListMenuItem* source);
bool process_weapons_crosshair_menu();

// 载具模型枪相关常量和变量
extern bool featureVehicleModelGun; // 载具模型枪开关
extern bool featureVehicleModelGunUpdated; // 载具模型枪状态更新标志
extern bool featurePedModelGun; // 角色模型枪开关
extern bool featurePedModelGunUpdated; // 角色模型枪状态更新标志

const std::vector<std::string> VEHICLE_MODEL_GUN_CATEGORIES{ "小型汽车", "轿车", "SUV", "轿跑车", "肌肉车", "经典跑车", "跑车", "超级跑车", "摩托车", "越野车", "开轮式", "特种车", "厢型车", "自行车", "直升机", "飞机", "船只" };

const std::vector<std::string> PED_MODEL_GUN_CATEGORIES{ "环境女性", "环境男性", "过场动画", "帮派女性", "帮派男性", "故事模式", "线上模式", "场景女性", "场景男性", "剧情场景女性", "剧情场景男性", "其他角色", "动物" };

const std::vector<std::string> MODEL_GUN_SPEED_CAPTIONS{ "最慢 [10]", "很慢 [20]", "慢速 [50]", "中低速 [100]", "默认速度 [200]", "中速 [300]", "中高速 [400]", "快速 [500]", "很快 [600]", "极快 [700]", "超快 [800]", "最快 [1000]" };
const float MODEL_GUN_SPEED_VALUES[] = { 10.0f, 20.0f, 50.0f, 100.0f, 200.0f, 300.0f, 400.0f, 500.0f, 600.0f, 700.0f, 800.0f, 1000.0f };

extern int VehicleModelGunCategoryIndex; // 载具分类索引
extern bool VehicleModelGunCategoryChanged; // 用于配置加载
extern int VehicleModelGunSpeedIndex; // 载具发射速度索引
extern bool VehicleModelGunSpeedChanged; // 用于配置加载
extern bool featureVehicleModelGunInvincible; // 载具无敌开关

extern int PedModelGunCategoryIndex; // 角色分类索引
extern bool PedModelGunCategoryChanged; // 用于配置加载
extern int PedModelGunSpeedIndex; // 角色发射速度索引
extern bool PedModelGunSpeedChanged; // 用于配置加载
extern bool featurePedModelGunInvincible; // 角色无敌开关

// 载具模型枪和角色模型枪函数声明
void onchange_vehicle_model_gun_category_index(int value, SelectFromListMenuItem* source);
void onchange_vehicle_model_gun_speed_index(int value, SelectFromListMenuItem* source);
void onchange_ped_model_gun_category_index(int value, SelectFromListMenuItem* source);
void onchange_ped_model_gun_speed_index(int value, SelectFromListMenuItem* source);
bool process_vehicle_model_gun_menu();
bool process_ped_model_gun_menu();
void fire_vehicle_model_gun();
void fire_ped_model_gun();
Hash get_random_vehicle_hash_by_category(int categoryIndex);
Hash get_random_ped_hash_by_category(int categoryIndex);

// 辅助函数声明
Vector3 DegreeToRadian(Vector3 angles);
Vector3 get_coords_from_gameplay_cam(float distance);
